export const Server = {
  endpoint: "https://cloud.appwrite.io/v1",
  projectID: "64cced226fa211528fbf",
  databaseID: "production",
  collectionIDChatMessages: "chat-messages",
  collectionIDChats: "chats",
  collectionIDUsers: "user-details",
  collectionIDGroups: "groups",
  collectionIDGroupMessages: "group-messages",
  bucketIDUserAvatars: "user-avatars",
  bucketIDChatAttachments: "chat-message-attachments",
  bucketIDGroupAvatars: "group-avatars",
  bucketIDGroupAttachments: "group-message-attachments",
  documentIDGlobalChat: "global-chat",
  functionIDFuncs: "funcs",
};
